# Семинар 2

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [11]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

In [10]:
vec1 = np.array([1, 2])

In [12]:
vec1

array([1, 2])

In [13]:
vec1.shape

(2,)

Число осей:

In [14]:
vec1.ndim

1

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [15]:
np.sum(vec)

21

In [16]:
np.sum(vec, axis=0)

array([ 9, 12])

In [17]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [18]:
vec.sum()

21

Транспонируем массив:

In [19]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [25]:
vec = vec.T

In [26]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [27]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [28]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
vec.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

Индексирование:

In [33]:
vec[:, 1]

array([2, 4, 6])

In [34]:
vec[2, :]

array([5, 6])

In [39]:
vec[1:2][0]

array([3, 4])

In [43]:
vec[1:2]

array([[3, 4]])

In [44]:
vec[:,1:2]

array([[2],
       [4],
       [6]])

In [35]:
vec[1:2, 0]

array([3])

In [45]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [47]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [50]:
vec > 1000

array([[False, False],
       [False, False],
       [False, False]])

In [49]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
vec[vec % 2 == 0]

array([], dtype=int64)

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [56]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

Массив из единиц:

In [57]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [58]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [69]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.hstack((vec, np.zeros((3,4))))

array([[1., 2., 0., 0., 0., 0.],
       [3., 4., 0., 0., 0., 0.],
       [5., 6., 0., 0., 0., 0.]])

In [68]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [70]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [71]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [72]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [73]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [74]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [75]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [80]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [81]:
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [83]:
np.dot(vec, vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [85]:
vec @ (vec).T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [86]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
vec + vec

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [91]:
np.arange(2).reshape(2, 1)

array([[0],
       [1]])

In [93]:
vec + np.arange(2)

array([[1, 3],
       [3, 5],
       [5, 7]])

Генерация случайных чисел:

In [95]:
np.random.rand(2, 3)

array([[0.29185829, 0.98583035, 0.28199762],
       [0.61262596, 0.87986869, 0.51128934]])

In [105]:
np.random.seed(0)
np.random.rand(2, 3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [106]:
np.random.rand(2, 3)

array([[0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

In [107]:
np.random.rand(2, 3)

array([[0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985]])

In [108]:
np.random.randn(3, 2)

array([[ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

In [110]:
np.random.normal(2, 1, size=(2, 1))

array([[1.25783498],
       [4.26975462]])

In [111]:
np.random.randint(5, 10, size=3)

array([5, 9, 5])

Почему вообще используют `numpy`?

In [112]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [116]:
B

array([[0.14562663, 0.76667869, 0.06222087, ..., 0.75705613, 0.10919213,
        0.03734355],
       [0.29645493, 0.06287043, 0.59222685, ..., 0.01967389, 0.1551379 ,
        0.09788901],
       [0.97479833, 0.4320212 , 0.21001516, ..., 0.65513603, 0.78605191,
        0.97501989],
       ...,
       [0.37468678, 0.83772472, 0.05285953, ..., 0.77750879, 0.99136207,
        0.68049656],
       [0.15184724, 0.68414319, 0.45448444, ..., 0.24188565, 0.31106251,
        0.88935507],
       [0.53610556, 0.893857  , 0.87858194, ..., 0.80313049, 0.46348752,
        0.93450995]])

In [117]:
C = np.zeros((n, n))

In [118]:
%%time

for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 20.1 s, sys: 105 ms, total: 20.2 s
Wall time: 20.3 s


In [119]:
%time a = 0

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.01 µs


In [120]:
%%time
C = A.dot(B)

CPU times: user 4.72 ms, sys: 2.83 ms, total: 7.55 ms
Wall time: 3.93 ms


In [137]:
vec2 = np.array([1,2,3, 5, 9])

In [128]:
vec2[::-1]

array([3, 2, 1])

In [139]:
vec2[vec2 % 2 == 1] = 8

In [140]:
vec2

array([8, 2, 8, 8, 8])

In [145]:
n = 5 

np.arange(2*n-1, 0, -2)

array([9, 7, 5, 3, 1])

In [150]:
vec3 = np.arange(1, 2*n, 2)

In [166]:
vec5 = np.array([0, 1, 2, 3, 4]) + 10

In [167]:
np.abs(vec5 - 1.33)

array([ 8.67,  9.67, 10.67, 11.67, 12.67])

In [170]:
[np.abs(vec5 - 1.33).argmin(), np.abs(vec5 - 1.33).argmax()]

[0, 4]

In [171]:
vec5[[np.abs(vec5 - 1.33).argmin(), np.abs(vec5 - 1.33).argmax()]]

array([10, 14])

### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐