## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [8]:
type(vec.shape)

tuple

In [9]:
vec.shape

(3, 2)

In [42]:
vec1 = np.array([1, 2])

In [43]:
vec1

array([1, 2])

In [62]:
vec1[1]

2

In [44]:
vec1.shape

(2,)

In [51]:
vec3 = vec1.reshape(1,2)

In [52]:
vec3

array([[1, 2]])

In [55]:
vec3[0][1]

2

In [56]:
vec1.reshape(2,1)

array([[1],
       [2]])

In [57]:
vec4 = vec1.reshape(2,1)

In [58]:
vec4

array([[1],
       [2]])

In [61]:
vec4[1][0]

2

Число осей:

In [14]:
vec1.ndim

1

In [15]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [16]:
np.sum(vec)

21

In [20]:
np.sum(vec, axis=0)

array([ 9, 12])

In [21]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [23]:
vec.sum()

21

Транспонируем массив:

In [27]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [34]:
vec = vec.T

In [35]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [36]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [37]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
vec.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

Индексирование:

In [63]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
vec[:, 1]

array([2, 4, 6])

In [71]:
vec[2, :]

array([5, 6])

In [82]:
vec[1:2, :]

array([[3, 4]])

In [88]:
vec[:, :]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
vec % 2

array([[1, 0],
       [1, 0],
       [1, 0]])

In [89]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [92]:
np.array([True, True]).shape

(2,)

In [93]:
vec.shape

(3, 2)

In [94]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [96]:
np.zeros((2, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [97]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [98]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [99]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.hstack((vec, np.zeros((3,4))))

array([[1., 2., 0., 0., 0., 0.],
       [3., 4., 0., 0., 0., 0.],
       [5., 6., 0., 0., 0., 0.]])

In [102]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [104]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [105]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [106]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [107]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [108]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [109]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [110]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [112]:
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [113]:
np.dot(vec, vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [114]:
vec @ (vec).T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [115]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
vec + vec

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [118]:
np.arange(2).reshape(2, 1)

array([[0],
       [1]])

In [119]:
np.arange(2)

array([0, 1])

In [122]:
vec + np.arange(2)

array([[1, 3],
       [3, 5],
       [5, 7]])

In [121]:
vec + np.arange(2).reshape(2, 1)

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

Генерация случайных чисел:

In [123]:
np.random.rand(2, 3)

array([[0.29522254, 0.91006738, 0.47019262],
       [0.71461038, 0.80835916, 0.52983706]])

In [128]:
np.random.randn(3, 2)

array([[-0.16623084,  0.26301551],
       [ 0.59313252, -0.76470129],
       [ 0.20660836,  1.1139725 ]])

In [125]:
np.random.normal(2, 1, size=(2, 1))

array([[ 2.17052496],
       [-0.30696291]])

In [129]:
np.random.randint(5, 10, size=3)

array([7, 6, 5])

Почему вообще используют `numpy`?

In [130]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [134]:
A.dtype

dtype('float64')

In [136]:
%time C = np.zeros((n, n))

CPU times: user 127 µs, sys: 56 µs, total: 183 µs
Wall time: 160 µs


In [137]:
%%time

for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 19.8 s, sys: 70.1 ms, total: 19.9 s
Wall time: 19.9 s


In [138]:
%%time
C1 = A.dot(B)

CPU times: user 4.98 ms, sys: 3.32 ms, total: 8.3 ms
Wall time: 9.48 ms


In [141]:
C1 - C

array([[ 0.00000000e+00,  2.84217094e-14,  0.00000000e+00, ...,
         2.84217094e-14,  0.00000000e+00,  2.84217094e-14],
       [ 1.42108547e-14, -5.68434189e-14,  1.42108547e-14, ...,
         1.42108547e-14,  4.26325641e-14,  0.00000000e+00],
       [ 1.42108547e-14, -1.42108547e-14,  2.84217094e-14, ...,
         0.00000000e+00,  0.00000000e+00,  2.84217094e-14],
       ...,
       [-2.84217094e-14, -1.42108547e-14, -2.84217094e-14, ...,
         0.00000000e+00, -1.42108547e-14,  1.42108547e-14],
       [-5.68434189e-14, -2.84217094e-14, -1.42108547e-14, ...,
        -1.42108547e-14, -7.10542736e-14,  0.00000000e+00],
       [-5.68434189e-14, -2.84217094e-14,  4.26325641e-14, ...,
        -4.26325641e-14, -5.68434189e-14,  2.84217094e-14]])

### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐